"""Initial migration with users table

Revision ID: 1a11e4dcd162
Revises: 91a4f0c8db07
Create Date: 2025-10-03 16:01:55.657057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a11e4dcd162'
down_revision: Union[str, Sequence[str], None] = '91a4f0c8db07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
