"""Refactor User, Message and Attachment models

Revision ID: c26beb1630bd
Revises: dee5ea463510
Create Date: 2025-10-06 10:49:25.752665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c26beb1630bd'
down_revision: Union[str, Sequence[str], None] = 'dee5ea463510'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attachments', sa.Column('original_filename', sa.String(), nullable=False))
    op.alter_column('attachments', 'file_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(op.f('attachments_user_id_fkey'), 'attachments', type_='foreignkey')
    op.drop_column('attachments', 'user_id')
    op.drop_column('attachments', 'file_send_date')
    op.drop_column('attachments', 'filename')
    op.add_column('messages', sa.Column('receiver_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'messages', 'users', ['receiver_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_column('messages', 'receiver_id')
    op.add_column('attachments', sa.Column('filename', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('attachments', sa.Column('file_send_date', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('attachments', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('attachments_user_id_fkey'), 'attachments', 'users', ['user_id'], ['id'])
    op.alter_column('attachments', 'file_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('attachments', 'original_filename')
    # ### end Alembic commands ###
