services:
  # для бекенду (FastAPI)
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/src:/app
    # докер-композ підставить сюди ДБ-урл з файлу .енв, а env_file передасть ВСІ змінні з .унв всередину контейнера для пайтона:
    env_file:
      - ./.env
    depends_on:
      - db
    restart: always

  # для фронтенду (React)
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      # кажемо Docker не чіпати папку node_modules всередині контейнера.
      # Це запобігає конфліктам між node_modules на моїй Windows і в контейнері (Linux).
      - /app/node_modules
    depends_on:
      - backend
    restart: always
        
  # для бази даних (PostgreSQL)
  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    # беремо значення сікретів із .енв файлу
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    restart: always

volumes:
  postgres_data: